# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: api
generate:
  models: true
  chi-server: true
  strict-server: true
output: ./internal/server/server.gen.go