// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateEventRequest Данные для создания нового события
type CreateEventRequest struct {
	Description  *string            `json:"description,omitempty"`
	Duration     string             `json:"duration"`
	EventTime    time.Time          `json:"eventTime"`
	NotifyBefore *string            `json:"notifyBefore,omitempty"`
	Title        string             `json:"title"`
	UserId       openapi_types.UUID `json:"userId"`
}

// Error Стандартный формат ошибки
type Error struct {
	// Code HTTP статус код
	Code int32 `json:"code"`

	// Details Дополнительная информация об ошибке
	Details *string `json:"details,omitempty"`

	// Message Описание ошибки
	Message string `json:"message"`
}

// Event Полная модель события календаря
type Event struct {
	// Description Подробное описание события (опционально)
	Description *string `json:"description,omitempty"`

	// Duration Длительность события (формат длительности Go)
	Duration string `json:"duration"`

	// EventTime Дата и время события в формате RFC3339
	EventTime time.Time `json:"eventTime"`

	// Id Уникальный идентификатор события
	Id openapi_types.UUID `json:"id"`

	// NotifyBefore За сколько времени выслать уведомление (0 - без уведомления)
	NotifyBefore *string `json:"notifyBefore,omitempty"`

	// Title Заголовок события
	Title string `json:"title"`

	// UserId ID пользователя-владельца события
	UserId openapi_types.UUID `json:"userId"`
}

// UpdateEventRequest Данные для обновления события (все поля опциональны)
type UpdateEventRequest struct {
	Description  *string             `json:"description,omitempty"`
	Duration     *string             `json:"duration,omitempty"`
	EventTime    *time.Time          `json:"eventTime,omitempty"`
	NotifyBefore *string             `json:"notifyBefore,omitempty"`
	Title        *string             `json:"title,omitempty"`
	UserId       *openapi_types.UUID `json:"userId,omitempty"`
}

// ListEventsByDayParams defines parameters for ListEventsByDay.
type ListEventsByDayParams struct {
	// Date Дата в формате YYYY-MM-DD
	Date openapi_types.Date `form:"date" json:"date"`
}

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = CreateEventRequest

// UpdateEventJSONRequestBody defines body for UpdateEvent for application/json ContentType.
type UpdateEventJSONRequestBody = UpdateEventRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получить список событий за указанный день
	// (GET /events)
	ListEventsByDay(w http.ResponseWriter, r *http.Request, params ListEventsByDayParams)
	// Создать новое событие
	// (POST /events)
	CreateEvent(w http.ResponseWriter, r *http.Request)
	// Получить события за месяц, содержащий указанную дату
	// (GET /events/month/{date})
	ListEventsByMonth(w http.ResponseWriter, r *http.Request, date openapi_types.Date)
	// Получить события за неделю, содержащую указанную дату
	// (GET /events/week/{date})
	ListEventsByWeek(w http.ResponseWriter, r *http.Request, date openapi_types.Date)
	// Удалить событие
	// (DELETE /events/{id})
	DeleteEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Получить событие по ID
	// (GET /events/{id})
	GetEventById(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Обновить существующее событие
	// (PUT /events/{id})
	UpdateEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Получить список событий за указанный день
// (GET /events)
func (_ Unimplemented) ListEventsByDay(w http.ResponseWriter, r *http.Request, params ListEventsByDayParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать новое событие
// (POST /events)
func (_ Unimplemented) CreateEvent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить события за месяц, содержащий указанную дату
// (GET /events/month/{date})
func (_ Unimplemented) ListEventsByMonth(w http.ResponseWriter, r *http.Request, date openapi_types.Date) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить события за неделю, содержащую указанную дату
// (GET /events/week/{date})
func (_ Unimplemented) ListEventsByWeek(w http.ResponseWriter, r *http.Request, date openapi_types.Date) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удалить событие
// (DELETE /events/{id})
func (_ Unimplemented) DeleteEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить событие по ID
// (GET /events/{id})
func (_ Unimplemented) GetEventById(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить существующее событие
// (PUT /events/{id})
func (_ Unimplemented) UpdateEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListEventsByDay operation middleware
func (siw *ServerInterfaceWrapper) ListEventsByDay(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEventsByDayParams

	// ------------- Required query parameter "date" -------------

	if paramValue := r.URL.Query().Get("date"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "date", r.URL.Query(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEventsByDay(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateEvent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEvent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEventsByMonth operation middleware
func (siw *ServerInterfaceWrapper) ListEventsByMonth(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "date" -------------
	var date openapi_types.Date

	err = runtime.BindStyledParameterWithOptions("simple", "date", chi.URLParam(r, "date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEventsByMonth(w, r, date)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEventsByWeek operation middleware
func (siw *ServerInterfaceWrapper) ListEventsByWeek(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "date" -------------
	var date openapi_types.Date

	err = runtime.BindStyledParameterWithOptions("simple", "date", chi.URLParam(r, "date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEventsByWeek(w, r, date)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteEvent operation middleware
func (siw *ServerInterfaceWrapper) DeleteEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventById operation middleware
func (siw *ServerInterfaceWrapper) GetEventById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventById(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateEvent operation middleware
func (siw *ServerInterfaceWrapper) UpdateEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events", wrapper.ListEventsByDay)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/events", wrapper.CreateEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events/month/{date}", wrapper.ListEventsByMonth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events/week/{date}", wrapper.ListEventsByWeek)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/events/{id}", wrapper.DeleteEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events/{id}", wrapper.GetEventById)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/events/{id}", wrapper.UpdateEvent)
	})

	return r
}

type ListEventsByDayRequestObject struct {
	Params ListEventsByDayParams
}

type ListEventsByDayResponseObject interface {
	VisitListEventsByDayResponse(w http.ResponseWriter) error
}

type ListEventsByDay200JSONResponse []Event

func (response ListEventsByDay200JSONResponse) VisitListEventsByDayResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListEventsByDay400JSONResponse Error

func (response ListEventsByDay400JSONResponse) VisitListEventsByDayResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListEventsByDay500JSONResponse Error

func (response ListEventsByDay500JSONResponse) VisitListEventsByDayResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateEventRequestObject struct {
	Body *CreateEventJSONRequestBody
}

type CreateEventResponseObject interface {
	VisitCreateEventResponse(w http.ResponseWriter) error
}

type CreateEvent201JSONResponse Event

func (response CreateEvent201JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateEvent400JSONResponse Error

func (response CreateEvent400JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateEvent500JSONResponse Error

func (response CreateEvent500JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListEventsByMonthRequestObject struct {
	Date openapi_types.Date `json:"date"`
}

type ListEventsByMonthResponseObject interface {
	VisitListEventsByMonthResponse(w http.ResponseWriter) error
}

type ListEventsByMonth200JSONResponse []Event

func (response ListEventsByMonth200JSONResponse) VisitListEventsByMonthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListEventsByMonth400JSONResponse Error

func (response ListEventsByMonth400JSONResponse) VisitListEventsByMonthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListEventsByMonth500JSONResponse Error

func (response ListEventsByMonth500JSONResponse) VisitListEventsByMonthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListEventsByWeekRequestObject struct {
	Date openapi_types.Date `json:"date"`
}

type ListEventsByWeekResponseObject interface {
	VisitListEventsByWeekResponse(w http.ResponseWriter) error
}

type ListEventsByWeek200JSONResponse []Event

func (response ListEventsByWeek200JSONResponse) VisitListEventsByWeekResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListEventsByWeek400JSONResponse Error

func (response ListEventsByWeek400JSONResponse) VisitListEventsByWeekResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListEventsByWeek500JSONResponse Error

func (response ListEventsByWeek500JSONResponse) VisitListEventsByWeekResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteEventRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteEventResponseObject interface {
	VisitDeleteEventResponse(w http.ResponseWriter) error
}

type DeleteEvent204Response struct {
}

func (response DeleteEvent204Response) VisitDeleteEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteEvent404JSONResponse Error

func (response DeleteEvent404JSONResponse) VisitDeleteEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteEvent500JSONResponse Error

func (response DeleteEvent500JSONResponse) VisitDeleteEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetEventByIdRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetEventByIdResponseObject interface {
	VisitGetEventByIdResponse(w http.ResponseWriter) error
}

type GetEventById200JSONResponse Event

func (response GetEventById200JSONResponse) VisitGetEventByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEventById404JSONResponse Error

func (response GetEventById404JSONResponse) VisitGetEventByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetEventById500JSONResponse Error

func (response GetEventById500JSONResponse) VisitGetEventByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateEventRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateEventJSONRequestBody
}

type UpdateEventResponseObject interface {
	VisitUpdateEventResponse(w http.ResponseWriter) error
}

type UpdateEvent200JSONResponse Event

func (response UpdateEvent200JSONResponse) VisitUpdateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateEvent400JSONResponse Error

func (response UpdateEvent400JSONResponse) VisitUpdateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateEvent404JSONResponse Error

func (response UpdateEvent404JSONResponse) VisitUpdateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateEvent500JSONResponse Error

func (response UpdateEvent500JSONResponse) VisitUpdateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Получить список событий за указанный день
	// (GET /events)
	ListEventsByDay(ctx context.Context, request ListEventsByDayRequestObject) (ListEventsByDayResponseObject, error)
	// Создать новое событие
	// (POST /events)
	CreateEvent(ctx context.Context, request CreateEventRequestObject) (CreateEventResponseObject, error)
	// Получить события за месяц, содержащий указанную дату
	// (GET /events/month/{date})
	ListEventsByMonth(ctx context.Context, request ListEventsByMonthRequestObject) (ListEventsByMonthResponseObject, error)
	// Получить события за неделю, содержащую указанную дату
	// (GET /events/week/{date})
	ListEventsByWeek(ctx context.Context, request ListEventsByWeekRequestObject) (ListEventsByWeekResponseObject, error)
	// Удалить событие
	// (DELETE /events/{id})
	DeleteEvent(ctx context.Context, request DeleteEventRequestObject) (DeleteEventResponseObject, error)
	// Получить событие по ID
	// (GET /events/{id})
	GetEventById(ctx context.Context, request GetEventByIdRequestObject) (GetEventByIdResponseObject, error)
	// Обновить существующее событие
	// (PUT /events/{id})
	UpdateEvent(ctx context.Context, request UpdateEventRequestObject) (UpdateEventResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListEventsByDay operation middleware
func (sh *strictHandler) ListEventsByDay(w http.ResponseWriter, r *http.Request, params ListEventsByDayParams) {
	var request ListEventsByDayRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListEventsByDay(ctx, request.(ListEventsByDayRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEventsByDay")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListEventsByDayResponseObject); ok {
		if err := validResponse.VisitListEventsByDayResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateEvent operation middleware
func (sh *strictHandler) CreateEvent(w http.ResponseWriter, r *http.Request) {
	var request CreateEventRequestObject

	var body CreateEventJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEvent(ctx, request.(CreateEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateEventResponseObject); ok {
		if err := validResponse.VisitCreateEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListEventsByMonth operation middleware
func (sh *strictHandler) ListEventsByMonth(w http.ResponseWriter, r *http.Request, date openapi_types.Date) {
	var request ListEventsByMonthRequestObject

	request.Date = date

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListEventsByMonth(ctx, request.(ListEventsByMonthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEventsByMonth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListEventsByMonthResponseObject); ok {
		if err := validResponse.VisitListEventsByMonthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListEventsByWeek operation middleware
func (sh *strictHandler) ListEventsByWeek(w http.ResponseWriter, r *http.Request, date openapi_types.Date) {
	var request ListEventsByWeekRequestObject

	request.Date = date

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListEventsByWeek(ctx, request.(ListEventsByWeekRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEventsByWeek")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListEventsByWeekResponseObject); ok {
		if err := validResponse.VisitListEventsByWeekResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteEvent operation middleware
func (sh *strictHandler) DeleteEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteEventRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteEvent(ctx, request.(DeleteEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteEventResponseObject); ok {
		if err := validResponse.VisitDeleteEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEventById operation middleware
func (sh *strictHandler) GetEventById(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetEventByIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEventById(ctx, request.(GetEventByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEventById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEventByIdResponseObject); ok {
		if err := validResponse.VisitGetEventByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateEvent operation middleware
func (sh *strictHandler) UpdateEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateEventRequestObject

	request.Id = id

	var body UpdateEventJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateEvent(ctx, request.(UpdateEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateEventResponseObject); ok {
		if err := validResponse.VisitUpdateEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
