logger:
  level: INFO
  filename: "logs/calendar_scheduler.log"

storage:
  mode: sql
  dsn: postgres://postgres:123456@postgres:5432/template2?sslmode=disable

kafka:
  brokers:
    - kafka:9092
  group-id: storer-group
  timeout: 10s
  topics:
    topic_notifications: notifications